# Version: 1.0
# Author: Mohamed Hammd
# License: GPL3+
# URL: https://steelbore.com

# Steelbore Hyprland Theme

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = rgba(4b7eb0ff) rgba(d98e32ff) 45deg
    col.inactive_border = rgba(050530ff)
    layout = dwindle
}

decoration {
    rounding = 4
    
    blur {
        enabled = true
        size = 3
        passes = 1
    }

    drop_shadow = yes
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(000027ee)
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
}
